# <h1><center>Data Science - NumPy</center></h1>

# <div style="text-align: left"> Task 1 </div>

In [2]:
import numpy as np

In [3]:
array_1 = np.arange(0, 10)

In [4]:
print(array_1)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
array_2 = np.ones(9, dtype=bool).reshape(3, 3)

In [6]:
print(array_2)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [7]:
array_3 = np.arange(10)

In [8]:
print(array_3[array_3%2==1])

[1 3 5 7 9]


In [9]:
array_4 = np.arange(10)
array_4[array_4%2==1] = -1

In [10]:
print(array_4)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [11]:
array_5 = np.arange(4).reshape(2,2)

In [12]:
print(array_5)

[[0 1]
 [2 3]]


In [13]:
a = np.arange(3, 12).reshape(3,3)
b = np.arange(6, 15).reshape(3,3)

In [14]:
c = np.dot(a, b)
sum = np.sum(c)

In [15]:
print (sum)

1944


# <div style="text-align: left"> Extension </div>

# <div style="text-align: left"> Task 1 </div>

In [16]:
type_1 =[1, 1, 1]
type_2 =[2, 2, 2]
type_3 =[3, 3, 3]
type_123 =[1, 2, 3]
type_123_1 =[1, 2, 3]
type_123_2 =[1, 2, 3]

In [17]:
print (type_1 + type_2 + type_3 + type_123 + type_123_1 + type_123_2)

[1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


# <div style="text-align: left"> Task 2 </div>

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8,9])
c = np.newarray1d(a,b)

In [19]:
print(c)

[[114 126 138]
 [195 216 237]
 [276 306 336]]


# <div style="text-align: left"> Task 3 </div>

In [20]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8,9])

In [21]:
print(a[3:7])

[4 5]


In [22]:
print(b[3:7])

[7 8 9]


In [23]:
print(sum)

1944
